Move reactified components from embeds
micnews/article-json-react-embeds pull request #1
Opened 2017-04-17 14:08 UTC by ellell

Breaking out the render part of [embeds](https://github.com/micnews/embeds), converted to react. Used https://github.com/micnews/embeds/pull/50 as base but upgraded to latest miclint and some minor adjustments for getting the code coverage to 100%! 

Type: Major (first version)

2017-04-17 15:32 UTC, ryanscottaudio commented on lib/types/instagram.js
> +const blackquoteStyle = {
prob should be called `blockquoteStyle` right? as opposed to `blackquoteStyle`

2017-04-17 15:47 UTC, ryanscottaudio commented on lib/render-iframe.js
> +  src: React.PropTypes.string,
this should be required, right?

2017-04-17 15:49 UTC, ryanscottaudio commented on lib/types/facebook.js
> +  url: React.PropTypes.string,
shouldn't all of these be required?

2017-04-17 15:49 UTC, ryanscottaudio commented on lib/types/facebook.js
> +  url: React.PropTypes.string,
i think these should be required too

2017-04-17 15:53 UTC, ryanscottaudio commented on lib/types/twitter.js
> +  user: React.PropTypes.string,
seems like this is actually a `shape({ name: PropTypes.string, slug: PropTypes.string })`

2017-04-17 16:09 UTC, ryanscottaudio requested changes
a lot of these proptypes need to be `isRequired` or changed in some way

2017-04-18 08:29 UTC, ellell commented
@ryanscottaudio Thanks, I just moved what was in the react branch in `embeds` and didn't take a closer look at it, but I'll look into fixing what needs to be required an not!

2017-04-18 09:38 UTC, ellell commented on lib/types/facebook.js
> +  url: React.PropTypes.string,
I updated url to be required, because technically it's the only one that is required to render valid facebook embed html, the other ones are just used in the preview before the embed has been parsed and processed by the fb sdk. We could definitely handle missing values a bit more graceful, but don't think it's necessary to prioritize right now and I rather not try to change any functionality from [embeds](https://github.com/micnews/embeds) in this PR. Sounds good?

2017-04-18 09:38 UTC, ellell commented on lib/types/facebook.js
> +  url: React.PropTypes.string,
See https://github.com/micnews/article-json-react-embeds/pull/1/files#r111910316

2017-04-18 09:43 UTC, ellell commented
@ryanscottaudio Updated!

2017-04-18 10:32 UTC, kesla commented
Why are we not using flow here?

2017-04-18 10:33 UTC, ellell commented
@kesla because I just broke out whatever was in the react branch in embeds, didn't update it.

2017-04-18 10:50 UTC, kesla commented
ok, so a suggestion here then would be to move to flow rather than updating legacy proptypes! :)

2017-04-18 10:54 UTC, ellell commented
oki I'll fix

2017-04-20 15:30 UTC, ryanscottaudio approved these changes

2017-04-24 08:22 UTC, merged